language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t doronma/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true doronma/docker-react npm run test -- --coverage
